name: test
on: [push, pull_request]

jobs:
  rescript:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - macos-10.15

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - run: npm install esy
    - run: echo PATH=$(pwd)/node_modules/.bin:$PATH >> $GITHUB_ENV
    - run: make -C test/bucklescript full-test
    - if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: bash ./test/ci/travis-binaries.sh

  opam:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        ocaml:
        - 4.13.1
        - 4.12.1
        - 4.11.2
        - 4.10.2
        - 4.09.1
        - 4.08.1
        - 4.07.1
        - 4.06.1
        - 4.05.0
        - 4.04.2
        include:
        - os: macos-latest
          ocaml: 4.13.1

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml }}
    - run: opam install --deps-only --yes .

    - run: opam exec -- make build
    - run: opam exec -- make test
